# Generated by Django 3.1.4 on 2021-05-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_projectmodel_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='css',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='database',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='django',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='html',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='javascript',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='python',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='tensorflow',
            field=models.BooleanField(default=False),
        ),
    ]
